const characterLatex = {
	"연산자": [
		{ name: "-", latex: "-" },
		{ name: "+", latex: "+" },
		{ name: "×", latex: "\\times" },
		{ name: "÷", latex: "\\div" },
		{ name: "±", latex: "\\pm" },
		{ name: "∫", latex: "\\sint" },
		{ name: "∬", latex: "\\siint" },
		{ name: "∮", latex: "\\soint" },
		{ name: "√", latex: "\\sqrt" },
		{ name: "∑", latex: "\\sum" },
		{ name: "lim", latex: "\\lim" },
		{ name: "=", latex: "=" },
		{ name: "≠", latex: "\\ne" },
		{ name: "≒", latex: "\\fallingdotseq" },
		{ name: ">", latex: ">" },
		{ name: "<", latex: "<" },
		{ name: "≤", latex: "\\le" },
		{ name: "≥", latex: "\\ge" },
		{ name: "→", latex: "\\to" },
		{ name: "←", latex: "\\gets" },
		{ name: "∞", latex: "\\infty" },
		{ name: "∴", latex: "\\therefore" },
		{ name: "∵", latex: "\\because" },
	],
	"문자": [
		{ name: "α", latex: "\\alpha" },
		{ name: "β", latex: "\\beta" },
		{ name: "γ", latex: "\\gamma" },
		{ name: "δ", latex: "\\delta" },
		{ name: "ε", latex: "\\epsilon" },
		{ name: "ζ", latex: "\\zeta" },
		{ name: "η", latex: "\\eta" },
		{ name: "θ", latex: "\\theta" },
		{ name: "ι", latex: "\\iota" },
		{ name: "κ", latex: "\\kappa" },
		{ name: "λ", latex: "\\lambda" },
		{ name: "μ", latex: "\\mu" },
		{ name: "ν", latex: "\\nu" },
		{ name: "ξ", latex: "\\xi" },
		{ name: "ο", latex: "\\omikron" },
		{ name: "π", latex: "\\pi" },
		{ name: "ρ", latex: "\\rho" },
		{ name: "σ", latex: "\\sigma" },
		{ name: "τ", latex: "\\tau" },
		{ name: "υ", latex: "\\upsilon" },
		{ name: "φ", latex: "\\phi" },
		{ name: "χ", latex: "\\chi" },
		{ name: "ψ", latex: "\\psi" },
		{ name: "ω", latex: "\\omega" },
	],
	"수식": [
		{ name: "근의 공식", latex: "\\frac{-b\\pm \\sqrt{b^2-4ac}}{2a}" },
		{ name: "이차 방정식", latex: "ax^2+bx+c=0" },
	],
};

export default characterLatex;
