const characterLatex = {
	operator: [
		{ symbol: "-", name: "minus", latex: "-", isSymbol: true },
		{ symbol: "+", name: "plus", latex: "+", isSymbol: true },
		{ symbol: "×", name: "times", latex: "\\times", isSymbol: true },
		{ symbol: "÷", name: "division", latex: "\\div", isSymbol: true },
		{ symbol: "±", name: "plus-minus", latex: "\\pm", isSymbol: true },
		{ symbol: "=", name: "equal", latex: "=", isSymbol: true },
		{ symbol: "≠", name: "not equal", latex: "\\ne", isSymbol: true },
		// { symbol: "≒", name: "", latex: "\\fallingdotseq", isSymbol: true },
		{ symbol: ">", name: "greater than", latex: ">", isSymbol: true },
		{ symbol: "<", name: "less than", latex: "<", isSymbol: true },
		{ symbol: "≥", name: "greater than or equal to", latex: "\\ge", isSymbol: true },
		{ symbol: "≤", name: "less than or equal to", latex: "\\le", isSymbol: true },
		{ symbol: "→", name: "right arrow", latex: "\\to", isSymbol: true },
		{ symbol: "←", name: "left arrow", latex: "\\gets", isSymbol: true },
		{ symbol: "↑", name: "up arrow", latex: "\\uparrow", isSymbol: true },
		{ symbol: "↓", name: "down arrow", latex: "\\downarrow", isSymbol: true },
		{ symbol: "∞", name: "infinity", latex: "\\infty", isSymbol: true },
		{ symbol: "∴", name: "therefore", latex: "\\therefore", isSymbol: true },
		{ symbol: "∵", name: "because", latex: "\\because", isSymbol: true },
	],
	character: [
		{ symbol: "α", name: "alpha", latex: "\\alpha", isSymbol: true },
		{ symbol: "β", name: "beta", latex: "\\beta", isSymbol: true },
		{ symbol: "γ", name: "gamma", latex: "\\gamma", isSymbol: true },
		{ symbol: "δ", name: "delta", latex: "\\delta", isSymbol: true },
		{ symbol: "ε", name: "epsilon", latex: "\\epsilon", isSymbol: true },
		{ symbol: "ζ", name: "zeta", latex: "\\zeta", isSymbol: true },
		{ symbol: "η", name: "eta", latex: "\\eta", isSymbol: true },
		{ symbol: "θ", name: "theta", latex: "\\theta", isSymbol: true },
		{ symbol: "ι", name: "iota", latex: "\\iota", isSymbol: true },
		{ symbol: "κ", name: "kappa", latex: "\\kappa", isSymbol: true },
		{ symbol: "λ", name: "lambda", latex: "\\lambda", isSymbol: true },
		{ symbol: "μ", name: "mu", latex: "\\mu", isSymbol: true },
		{ symbol: "ν", name: "nu", latex: "\\nu", isSymbol: true },
		{ symbol: "ξ", name: "xi", latex: "\\xi", isSymbol: true },
		// { symbol: "ο", name: "omicron", latex: "\\omikron", isSymbol: true },
		{ symbol: "π", name: "pi", latex: "\\pi", isSymbol: true },
		{ symbol: "ρ", name: "rho", latex: "\\rho", isSymbol: true },
		{ symbol: "σ", name: "sigma", latex: "\\sigma", isSymbol: true },
		{ symbol: "τ", name: "tau", latex: "\\tau", isSymbol: true },
		{ symbol: "υ", name: "upsilon", latex: "\\upsilon", isSymbol: true },
		{ symbol: "φ", name: "phi", latex: "\\phi", isSymbol: true },
		{ symbol: "χ", name: "chi", latex: "\\chi", isSymbol: true },
		{ symbol: "ψ", name: "psi", latex: "\\psi", isSymbol: true },
		{ symbol: "ω", name: "omega", latex: "\\omega", isSymbol: true },
	],
	formula: [
		{ symbol: "log", name: "log", latex: "\\log_{ }", isSymbol: true },
		{ symbol: "ln", name: "ln", latex: "\\ln", isSymbol: true },
		{ symbol: "lim", name: "limit", latex: "\\lim_{ }", isSymbol: true },
		{ symbol: "\\sqrt{\\ }", name: "square root", latex: "\\sqrt{ }", isSymbol: true },
		{ symbol: "Σ", name: "sigma", latex: "\\sum", isSymbol: true },
		{ symbol: "∏", name: "product", latex: "\\prod", isSymbol: false },
		{ symbol: "∫", name: "integral", latex: "\\int", isSymbol: false },
		{ symbol: "∮", name: "contour integral", latex: "\\oint_{ }^{ }", isSymbol: true },
		// { symbol: "∬", name: "", latex: "\\iint", isSymbol: true },
	],
};

export default characterLatex;
