const mathquillLatex = {
	// "\\Downarrow": "\\Downarrow",
	// "\\Im": "\\Im",
	// "\\Leftarrow": "\\Leftarrow",
	// "\\Leftrightarrow": "\\Leftrightarrow",
	// "\\Longleftarrow": "\\Longleftarrow",
	// "\\Longleftrightarrow": "\\Longleftrightarrow",
	// "\\Longrightarrow": "\\Longrightarrow",
	// "\\Re": "\\Re",
	// "\\Rightarrow": "\\Rightarrow",
	// "\\Sigma": "\\Sigma",
	// "\\Uparrow": "\\Uparrow",
	// "\\Updownarrow": "\\Updownarrow",
	// "\\Upsilon": "\\Upsilon",
	"\\aleph": "\\aleph",
	"\\alpha": "\\alpha",
	"\\amalg": "\\amalg",
	"\\angle": "\\angle",
	"\\approx": "\\approx",
	"\\ast": "\\ast",
	"\\because": "\\because",
	"\\beta": "\\beta",
	"\\bigcap": "\\bigcap",
	"\\bigcirc": "\\bigcirc",
	"\\bigcup": "\\bigcup",
	"\\bigodot": "\\bigodot",
	"\\bigoplus": "\\bigoplus",
	"\\bigotimes": "\\bigotimes",
	"\\bigsqcup": "\\bigsqcup",
	"\\bigtriangledown": "\\bigtriangledown",
	"\\bigtriangleup": "\\bigtriangleup",
	"\\biguplus": "\\biguplus",
	"\\bigvee": "\\bigvee",
	"\\bigwedge": "\\bigwedge",
	"\\bot": "\\bot",
	"\\bowtie": "\\bowtie",
	"\\bullet": "\\bullet",
	"\\cap": "\\cap",
	"\\cdot": "\\cdot",
	"\\cdots": "\\cdots",
	"\\chi": "\\chi",
	"\\circ": "\\circ",
	"\\clubsuit": "\\clubsuit",
	"\\cup": "\\cup",
	"\\dagger": "\\dagger",
	"\\dashv": "\\dashv",
	"\\ddagger": "\\ddagger",
	"\\ddots": "\\ddots",
	"\\degree": "\\degree",
	"\\delta": "\\delta",
	"\\diamond": "\\diamond",
	"\\diamondsuit": "\\diamondsuit",
	"\\digamma": "\\digamma",
	"\\div": "\\div",
	"\\doteq": "\\doteq",
	"\\dots": "\\dots",
	"\\downarrow": "\\downarrow",
	"\\ell": "\\ell",
	"\\epsilon": "\\epsilon",
	"\\equiv": "\\equiv",
	"\\eta": "\\eta",
	"\\exists": "\\exists",
	"\\flat": "\\flat",
	"\\frown": "\\frown",
	"\\gamma": "\\gamma",
	"\\ge": "\\ge",
	"\\gets": "\\gets",
	"\\gg": "\\gg",
	"\\hbar": "\\hbar",
	"\\heartsuit": "\\heartsuit",
	"\\hookleftarrow": "\\hookleftarrow",
	"\\hookrightarrow": "\\hookrightarrow",
	"\\in": "\\in",
	"\\infty": "\\infty",
	"\\int": "\\int",
	"\\iota": "\\iota",
	"\\kappa": "\\kappa",
	"\\lambda": "\\lambda",
	"\\lbrace": "\\lbrace",
	"\\lceil": "\\lceil",
	"\\ldots": "\\ldots",
	"\\le": "\\le",
	"\\leftarrow": "\\leftarrow",
	"\\leftharpoondown": "\\leftharpoondown",
	"\\leftharpoonup": "\\leftharpoonup",
	"\\leftrightarrow": "\\leftrightarrow",
	"\\lfloor": "\\lfloor",
	"\\lim_": "\\lim_{ }",
	"\\ll": "\\ll",
	"\\ln": "\\ln",
	"\\log_": "\\log_{ }",
	"\\longleftarrow": "\\longleftarrow",
	"\\longleftrightarrow": "\\longleftrightarrow",
	"\\longrightarrow": "\\longrightarrow",
	"\\mapsto": "\\mapsto",
	"\\measuredangle": "\\measuredangle",
	"\\mid": "\\mid",
	"\\models": "\\models",
	"\\mp": "\\mp",
	"\\mu": "\\mu",
	"\\nabla": "\\nabla",
	"\\natural": "\\natural",
	"\\ne": "\\ne",
	"\\nearrow": "\\nearrow",
	"\\neg": "\\neg",
	"\\nexists": "\\nexists",
	"\\ngtr": "\\ngtr",
	"\\ni": "\\ni",
	"\\nless": "\\nless",
	"\\nsubset": "\\nsubset",
	"\\nsubseteq": "\\nsubseteq",
	"\\nsupset": "\\nsupset",
	"\\nsupseteq": "\\nsupseteq",
	"\\nparallel": "\\nparallel",
	"\\nu": "\\nu",
	"\\nwarrow": "\\nwarrow",
	"\\odot": "\\odot",
	"\\oint": "\\oint",
	"\\oint_": "\\oint_{ }^{ }",
	"\\omega": "\\omega",
	"\\omikron": "\\omikron",
	"\\ominus": "\\ominus",
	"\\parallel": "\\parallel",
	"\\parallelogram": "\\parallelogram",
	"\\partial": "\\partial",
	"\\perp": "\\perp",
	"\\phi": "\\phi",
	"\\pi": "\\pi",
	"\\pm": "\\pm",
	"\\pounds": "\\pounds",
	"\\prec": "\\prec",
	"\\preceq": "\\preceq",
	"\\prod": "\\prod",
	"\\propto": "\\propto",
	"\\psi": "\\psi",
	"\\rbrace": "\\rbrace",
	"\\rceil": "\\rceil",
	"\\rfloor": "\\rfloor",
	"\\rho": "\\rho",
	"\\rightarrow": "\\rightarrow",
	"\\rightharpoondown": "\\rightharpoondown",
	"\\rightharpoonup": "\\rightharpoonup",
	"\\searrow": "\\searrow",
	"\\setminus": "\\setminus",
	"\\sharp": "\\sharp",
	"\\sigma": "\\sigma",
	"\\simeq": "\\simeq",
	"\\smile": "\\smile",
	"\\spadesuit": "\\spadesuit",
	"\\sqcap": "\\sqcap",
	"\\sqcup": "\\sqcup",
	"\\sqrt": "\\sqrt{ }",
	"\\sqsubset": "\\sqsubset",
	"\\sqsubseteq": "\\sqsubseteq",
	"\\sqsupset": "\\sqsupset",
	"\\sqsupseteq": "\\sqsupseteq",
	"\\square": "\\square",
	"\\subset": "\\subset",
	"\\subseteq": "\\subseteq",
	"\\succ": "\\succ",
	"\\succeq": "\\succeq",
	"\\sum": "\\sum",
	"\\supset": "\\supset",
	"\\supseteq": "\\supseteq",
	"\\surd": "\\surd",
	"\\swarrow": "\\swarrow",
	"\\tau": "\\tau",
	"\\therefore": "\\therefore",
	"\\theta": "\\theta",
	"\\times": "\\times",
	"\\to": "\\to",
	"\\top": "\\top",
	"\\triangle": "\\triangle",
	"\\triangleleft": "\\triangleleft",
	"\\triangleright": "\\triangleright",
	"\\uparrow": "\\uparrow",
	"\\updownarrow": "\\updownarrow",
	"\\uplus": "\\uplus",
	"\\upsilon": "\\upsilon",
	"\\varepsilon": "\\varepsilon",
	"\\varkappa": "\\varkappa",
	"\\varnothing": "\\varnothing",
	"\\varphi": "\\varphi",
	"\\varpi": "\\varpi",
	"\\varrho": "\\varrho",
	"\\varsigma": "\\varsigma",
	"\\vartheta": "\\vartheta",
	"\\vdash": "\\vdash",
	"\\vdots": "\\vdots",
	"\\vee": "\\vee",
	"\\wedge": "\\wedge",
	"\\wp": "\\wp",
	"\\wr": "\\wr",
	"\\xi": "\\xi",
	"\\zeta": "\\zeta",
};

export default mathquillLatex;
